name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'   # runs on version tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build exe
        run: |
          python -m PyInstaller --onefile --windowed password_generator.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: password-generator
          path: dist/password_generator.exe
