name: Build and Release Password Generator

on:
  push:
    tags:
      - 'v*'  # e.g., v1.0.0

permissions:
  contents: write  # allows creating releases and uploading assets

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build Windows exe
        run: |
          python -m PyInstaller --onefile --windowed password_generator.py

      - name: Upload Windows exe to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/password_generator.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build Mac app
        run: |
          python -m PyInstaller --onefile --windowed password_generator.py

      - name: Upload Mac binary to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/password_generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
